### ISSUE TITLE
Bro stop using TerraFirmaGreg in ur project name

### ISSUE THREAD

**Issue by Exzept1on** [dmkenza/tfg_ores#1]
We can write to the CurseForge administration on this topic, but I wanted to suggest solving it locally

**Comment by dmkenza** [comment]
Did you tired what people are suggesting you to add this mod?
I actually created it for your modpack, but you refuse to add.

I could rename to TerraFirmaGregTech-Ores.

**Comment by Exzept1on** [comment]
In fact, we already have ores with poor and rich variants in the modpack and no one offered us to add your mod, idk why u talking about this :(
